### ISSUE TITLE
找不到哈希函数

### ISSUE THREAD

**Issue by thouger** [Pr0214/findhash#4]
![image](https://user-images.githubusercontent.com/11767062/132654155-3ac96584-1ab8-4926-91d5-f6135751fb77.png)
so文件是从这里https://blog.csdn.net/qq_38851536/article/details/117418582
下载的，文章里面可以找的出来，我曾经试过也有一次找的出来，后来又找不出了
[liboasiscore.zip](https://github.com/Pr0214/findhash/files/7134982/liboasiscore.zip)

**Comment by Pr0214** [comment]
ida 使用7.5版本
